window.translations = {
    fr: {
        'page-title': 'Portfolio | Adjahossou Samuel - Développeur Web Fullstack',
        'all-projects-page-title': 'Projets Réalisés | Adjahossou Samuel',
        'services-page-title': 'Services & Expertise | Adjahossou Samuel',
        'cv-title': 'CV | Adjahossou Samuel',
        'logo-mon': 'Mon',
        'nav-home': 'Accueil',
        'nav-about': 'À propos',
        'nav-projects': 'Projets',
        'nav-skills': 'Compétences',
        'nav-cv': 'Mon CV',
        'nav-contact': 'Contact',
        'hero-badge': 'Disponible pour vos projets',
        'hero-title-tag': 'Développeur Full Stack',
        'hero-trait-1': '<i class="fas fa-rocket"></i> Passionné',
        'hero-trait-2': '<i class="fas fa-brain"></i> Curieux',
        'hero-trait-3': '<i class="fas fa-check-circle"></i> Rigoureux',
        'hero-desc': "Expert dans la conception d'expériences numériques modernes. Je combine créativité et rigueur technique pour transformer vos idées en solutions web performantes, utilisant les technologies les plus pointues du marché.",
        'hero-btn-explore': 'Explorer mes réalisations',
        'hero-btn-contact': 'Me contacter',
        'recent-projects-title': 'Réalisations Récentes',
        'badge-new': 'Nouveau',
        'badge-hot': 'Populaire',
        'btn-all-projects': 'Voir tous les projets <i class="fas fa-arrow-right"></i>',
        'all-projects-title': 'Toutes mes Réalisations',
        'all-projects-subtitle': 'Découvrez l\'ensemble de mes projets, du développement web aux applications complexes.',
        'contact-slide-title': 'Prêt à donner vie à vos projets ?',
        'contact-slide-intro': "Qu'il s'agisse d'une application web complexe ou d'une solution sur mesure, je transforme vos idées en réalité numérique performante et élégante.",
        'contact-loc-title': 'Localisation',
        'contact-follow-title': 'Suivez mon actualité',
        'btn-start-chat': 'Lancer la discussion <i class="fas fa-paper-plane" style="margin-left: 10px;"></i>',
        'about-title': 'À Propos de Moi',
        'about-subtitle': 'Étudiant en MIAGE & Développeur Full Stack',
        'about-p1': "Passionné par l'informatique, je suis actuellement étudiant en <strong>Licence 3 MIAGE</strong> à l'Université Polytechnique de Bingerville. Mon parcours est guidé par une curiosité insatiable et une rigueur qui me pousse à relever des défis technologiques complexes.",
        'about-p2': "À 19 ans, je combine mes études avec une pratique autodidacte intensive du développement web, me spécialisant dans les architectures modernes comme <strong>React</strong> et <strong>Spring Boot</strong>. Mon objectif est de créer des solutions numériques qui apportent une réelle valeur ajoutée.",
        'stat-projects': 'Projets',
        'stat-years': 'Ans',
        'stat-level': 'Niveau',
        'btn-path': '<i class="fas fa-graduation-cap" style="margin-right: 10px;"></i> Découvrir mon parcours',
        'btn-cv': '<i class="fas fa-file-alt" style="margin-right: 10px;"></i> Voir mon CV Complet',
        'btn-back-home': '<i class="fas fa-arrow-left"></i> Retour à l\'accueil',
        'skills-title': 'Mes Compétences',
        'projects-title': 'Mes Projets',
        'project-desc-label': '<strong>Description du projet</strong><br>',
        'path-title': 'Mon Parcours Académique',
        'contact-section-title': 'Contactez-moi',
        'contact-form-title': 'Envoyez-moi un message',
        'form-name': 'Votre nom',
        'form-email': 'Email',
        'form-email-placeholder': 'votre@email.com',
        'form-subject': 'Sujet de votre message',
        'form-message': 'Votre message...',
        'btn-send': '<span>Envoyer le message</span> <i class="fas fa-paper-plane"></i>',
        'footer-desc': "Conception et développement d'expériences numériques d'exception.",
        'footer-nav-title': 'Navigation',
        'footer-rights': 'Tous droits réservés.',
        'modal-problem': 'Le Problème',
        'modal-solution': 'La Solution',
        'modal-result': 'Le Résultat',
        'modal-description': 'Description',
        'modal-technologies': 'Technologies',
        'contact-talk-title': 'Parlons de votre projet',
        'contact-talk-desc': "Vous avez un projet en tête ? N'hésitez pas à me contacter. Je suis toujours disponible pour discuter de nouvelles idées et collaborations.",
        'contact-info-loc': 'Localisation',
        'contact-info-phone': 'Téléphone',
        'contact-info-avail': 'Disponibilité',
        'cv-title': 'CV - Adjahossou Samuel',
        'services-page-title': 'Services Proposés - Adjahossou Samuel',
        // Services
        'nav-services': 'Services',
        'services-title': 'Services Proposés',
        'service-1-title': 'Développement Web',
        'service-1-desc': 'Création de sites vitrines et plateformes sur mesure.',
        'service-2-title': 'Applications React',
        'service-2-desc': 'Interfaces dynamiques et robustes.',
        'service-3-title': 'Solutions Backend',
        'service-3-desc': 'APIs sécurisées et architectures évolutives.',
        'service-cta': 'Demander un devis',
        'quote-title': 'Demander un devis personnalisé',
        'quote-name': 'Votre Nom',
        'quote-email': 'Votre Email',
        'quote-service': 'Service souhaité',
        'quote-budget': 'Budget estimé',
        'quote-message': 'Détails de votre projet',
        'quote-send': 'Envoyer ma demande',
        'quote-success': 'Demande envoyée avec succès !',
        // CV
        'cv-contact': 'CONTACT',
        'cv-skills': 'COMPÉTENCES',
        'cv-languages': 'LANGUES',
        'cv-interests': 'CENTRES D\'INTÉRÊT',
        'cv-profile': 'PROFIL',
        'cv-education': 'FORMATION',
        'cv-experience': 'EXPÉRIENCES PROFESSIONNELLES',
        'cv-profile-text': 'Étudiant en informatique de 19 ans, passionné par le développement et les nouvelles technologies. Autodidacte, curieux et rigoureux, je suis constamment à la recherche de nouveaux défis pour apprendre et progresser.',
        'cv-lang-fr': 'Français',
        'cv-lang-en': 'Anglais',
        'cv-lang-es': 'Espagnol',
        'cv-interest-1': 'Basketball',
        'cv-interest-2': 'Voyages (découverte de nouvelles cultures)',
        'cv-interest-3': 'Lecture & Musique',
        'cv-interest-4': 'Documentaires (sciences, histoire)',
        'cv-edu-1-title': 'Licence 3 MIAGE (Méthodes Informatiques Appliquées à la Gestion des Entreprises)',
        'cv-edu-2-title': 'BACCALAURÉAT Série C',
        'cv-edu-3-title': 'Brevet d\'Études du Premier Cycle (BEPC)',
        'cv-exp-1-title': 'Développeur Full Stack - Projet SmartRDV',
        'cv-exp-1-sub': '<strong>Projet académique - Bingerville</strong> | Avril 2026 (en cours)',
        'cv-exp-1-li1': '<strong>Conception et développement</strong> d\'une application web de gestion de prise de rendez-vous',
        'cv-exp-1-li2': '<strong>Mise en place</strong> d\'une architecture Frontend (React + Vite) et Backend (Spring Boot)',
        'cv-exp-1-li3': '<strong>Implémentation</strong> d\'un système multi-rôles (Administrateur, Entreprise, Client)',
        'cv-exp-1-li4': '<strong>Développement des fonctionnalités :</strong>',
        'cv-exp-1-li4-s1': 'Authentification et gestion des utilisateurs',
        'cv-exp-1-li4-s2': 'Réservation de rendez-vous en ligne',
        'cv-exp-1-li4-s3': 'Tableaux de bord dynamiques selon le rôle',
        'cv-exp-1-li5': '<strong>Conception de la base de données</strong> (MySQL / XAMPP)',
        'cv-exp-2-title': 'Gérant de cybercafé',
        'cv-exp-2-sub': '<strong>Cybercafé – Adzopé</strong> | Juillet - Août 2024 (2 mois)',
        'cv-exp-2-li1': '<strong>Gestion technique :</strong> Maintenance et dépannage des ordinateurs',
        'cv-exp-2-li2': '<strong>Service client :</strong> Accompagnement des utilisateurs (internet, impression, scan)',
        'cv-exp-2-li3': '<strong>Gestion administrative :</strong> Suivi de la caisse, approvisionnement',
        'cv-exp-2-li4': 'Explications adaptées aux débutants en informatique',
        'form-sending': 'Envoi en cours...',
        'form-success': 'Message envoyé !',
        'form-success-full': 'Message envoyé avec succès ! Je vous répondrai dans les plus brefs délais.',
        'form-error-email': 'Veuillez entrer une adresse email valide.',
        'form-error-generic': 'Erreur lors de l\'envoi. Veuillez réessayer.'
    },
    en: {
        'page-title': 'Portfolio | Adjahossou Samuel - Fullstack Web Developer',
        'all-projects-page-title': 'Realized Projects | Adjahossou Samuel',
        'services-page-title': 'Services & Expertise | Adjahossou Samuel',
        'cv-title': 'Resume | Adjahossou Samuel',
        'logo-mon': 'My',
        'nav-home': 'Home',
        'nav-about': 'About',
        'nav-projects': 'Projects',
        'nav-skills': 'Skills',
        'nav-cv': 'My Resume',
        'nav-contact': 'Contact',
        'hero-badge': 'Available for your projects',
        'hero-title-tag': 'Full Stack Developer',
        'hero-trait-1': '<i class="fas fa-rocket"></i> Passionate',
        'hero-trait-2': '<i class="fas fa-brain"></i> Curious',
        'hero-trait-3': '<i class="fas fa-check-circle"></i> Rigorous',
        'hero-desc': 'Expert in designing modern digital experiences. I combine creativity and technical rigor to transform your ideas into high-performance web solutions, using cutting-edge technologies.',
        'hero-btn-explore': 'Explore my work',
        'hero-btn-contact': 'Contact me',
        'recent-projects-title': 'Recent Work',
        'badge-new': 'New',
        'badge-hot': 'Popular',
        'btn-all-projects': 'See all projects <i class="fas fa-arrow-right"></i>',
        'all-projects-title': 'All my Achievements',
        'all-projects-subtitle': 'Discover all my projects, from web development to complex applications.',
        'contact-slide-title': 'Ready to bring your projects to life?',
        'contact-slide-intro': 'Whether it is a complex web application or a custom solution, I transform your ideas into an elegant and high-performance digital reality.',
        'contact-loc-title': 'Location',
        'contact-follow-title': 'Follow my updates',
        'btn-start-chat': 'Start a discussion <i class="fas fa-paper-plane" style="margin-left: 10px;"></i>',
        'about-title': 'About Me',
        'about-subtitle': 'MIAGE Student & Full Stack Developer',
        'about-p1': 'Passionate about IT, I am currently a <strong>3rd-year MIAGE</strong> student at the Polytechnic University of Bingerville. My journey is guided by an insatiable curiosity and a rigor that pushes me to take on complex technological challenges.',
        'about-p2': 'At 19, I combine my studies with intensive self-taught web development practice, specializing in modern architectures like <strong>React</strong> and <strong>Spring Boot</strong>. My goal is to create digital solutions that bring real added value.',
        'stat-projects': 'Projects',
        'stat-years': 'Years',
        'stat-level': 'Level',
        'btn-path': '<i class="fas fa-graduation-cap" style="margin-right: 10px;"></i> Discover my background',
        'btn-cv': '<i class="fas fa-file-alt" style="margin-right: 10px;"></i> View my full Resume',
        'btn-back-home': '<i class="fas fa-arrow-left"></i> Back to home',
        'skills-title': 'My Skills',
        'projects-title': 'My Projects',
        'project-desc-label': '<strong>Project description</strong><br>',
        'path-title': 'My Academic Background',
        'contact-section-title': 'Contact Me',
        'contact-form-title': 'Send me a message',
        'form-name': 'Your Name',
        'form-email': 'Email',
        'form-email-placeholder': 'your@email.com',
        'form-subject': 'Message subject',
        'form-message': 'Your message...',
        'btn-send': '<span>Send message</span> <i class="fas fa-paper-plane"></i>',
        'footer-desc': 'Designing and developing exceptional digital experiences.',
        'footer-nav-title': 'Navigation',
        'footer-rights': 'All rights reserved.',
        'modal-problem': 'The Problem',
        'modal-solution': 'The Solution',
        'modal-result': 'The Result',
        'modal-description': 'Description',
        'modal-technologies': 'Technologies',
        'contact-talk-title': 'Let\'s talk about your project',
        'contact-talk-desc': "Have a project in mind? Feel free to contact me. I'm always available to discuss new ideas and collaborations.",
        'contact-info-loc': 'Location',
        'contact-info-phone': 'Phone',
        'contact-info-avail': 'Availability',
        'cv-title': 'Resume - Adjahossou Samuel',
        'services-page-title': 'Offered Services - Adjahossou Samuel',
        // Services
        'nav-services': 'Services',
        'services-title': 'Offered Services',
        'service-1-title': 'Web Development',
        'service-1-desc': 'Creation of showcase sites and custom platforms.',
        'service-2-title': 'React Applications',
        'service-2-desc': 'Dynamic and robust user interfaces.',
        'service-3-title': 'Backend Solutions',
        'service-3-desc': 'Secure APIs and scalable architectures.',
        'service-cta': 'Request a quote',
        'quote-title': 'Request a Custom Quote',
        'quote-name': 'Your Name',
        'quote-email': 'Your Email',
        'quote-service': 'Desired Service',
        'quote-budget': 'Estimated Budget',
        'quote-message': 'Project details',
        'quote-send': 'Send my request',
        'quote-success': 'Request sent successfully!',
        // CV
        'cv-contact': 'CONTACT',
        'cv-skills': 'SKILLS',
        'cv-languages': 'LANGUAGES',
        'cv-interests': 'INTERESTS',
        'cv-profile': 'PROFILE',
        'cv-education': 'EDUCATION',
        'cv-experience': 'PROFESSIONAL EXPERIENCE',
        'cv-profile-text': '19-year-old computer science student, passionate about development and new technologies. Self-taught, curious, and rigorous, I am constantly looking for new challenges to learn and grow.',
        'cv-lang-fr': 'French',
        'cv-lang-en': 'English',
        'cv-lang-es': 'Spanish',
        'cv-interest-1': 'Basketball',
        'cv-interest-2': 'Travel (discovering new cultures)',
        'cv-interest-3': 'Reading & Music',
        'cv-interest-4': 'Documentaries (science, history)',
        'cv-edu-1-title': '3rd Year MIAGE Bachelor (Methods Applied to Business Management)',
        'cv-edu-2-title': 'Scientific Baccalaureate (Série C)',
        'cv-edu-3-title': 'Junior High School Certificate (BEPC)',
        'cv-exp-1-title': 'Full Stack Developer - SmartRDV Project',
        'cv-exp-1-sub': '<strong>Academic Project - Bingerville</strong> | April 2026 (ongoing)',
        'cv-exp-1-li1': '<strong>Design and development</strong> of a web application for appointment management',
        'cv-exp-1-li2': '<strong>Setting up</strong> a Frontend (React + Vite) and Backend (Spring Boot) architecture',
        'cv-exp-1-li3': '<strong>Implementation</strong> of a multi-role system (Admin, Company, Client)',
        'cv-exp-1-li4': '<strong>Feature development:</strong>',
        'cv-exp-1-li4-s1': 'Authentication and user management',
        'cv-exp-1-li4-s2': 'Online appointment booking',
        'cv-exp-1-li4-s3': 'Dynamic dashboards based on roles',
        'cv-exp-1-li5': '<strong>Database design</strong> (MySQL / XAMPP)',
        'cv-exp-2-title': 'Cybercafe Manager',
        'cv-exp-2-sub': '<strong>Cybercafe – Adzopé</strong> | July - August 2024 (2 months)',
        'cv-exp-2-li1': '<strong>Technical management:</strong> Computer maintenance and troubleshooting',
        'cv-exp-2-li2': '<strong>Customer service:</strong> Assisting users (internet, printing, scanning)',
        'cv-exp-2-li3': '<strong>Administrative management:</strong> Cash tracking, supplies procurement',
        'cv-exp-2-li4': '<strong>Teaching:</strong> Explanations adapted to IT beginners',
        'form-sending': 'Sending...',
        'form-success': 'Message sent!',
        'form-success-full': 'Message sent successfully! I will get back to you as soon as possible.',
        'form-error-email': 'Please enter a valid email address.',
        'form-error-generic': 'Error during sending. Please try again.'
    }
};
